# Dataset
dataset: H36M
data: data/H36M

# Training information
workers: 4
epochs: 30
start_epoch: 0
schedule: 30
batch_size: 32
lr: 0.001
momentum: 0.9
weight_decay: 0.0001
print_freq: 10
pretrained: True
gpu: 0
val_schedule: 20
curriculum: 4
visualize: True

# Path to save checkpoint
checkpoint: checkpoint/H36M
# Specify number of keypoints
nkpts: 10

# Hyperparameters
image_size: 128
frame_gap: 20
bounding_box: True

perc_weight: [100.0, 1.6, 2.3, 1.8, 2.8, 100.0]

# Specify model path
# resume: checkpoint/CalMS21
evaluate: False
